name: CI

on:
  push:
    branches: [main, 'v[0-9]+.[0-9]+']
  pull_request:
    branches: [main]

jobs:
  lint:
    uses: ./.github/workflows/_reusable-lint.yml

  test:
    uses: ./.github/workflows/_reusable-test.yml
    with:
      coverage-threshold: 90
